[package]
name = "mlkc-lower"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mlkc-diagnostics.workspace = true
mlkc-hir-def.workspace = true
mlkc-intern.workspace = true
mlkc-rowan.workspace = true
mlkc-span.workspace = true
mlkc-syntax.workspace = true
mlkc-vfs.workspace = true

[dev-dependencies]
insta.workspace = true
mlkc-parser.workspace = true
mlkc-parser-core.workspace = true

[lints]
workspace = true
