[package]
name = "mlkc-wasm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mlkc-codegen-wasm.workspace = true
mlkc-diagnostics.workspace = true
mlkc-driver.workspace = true
mlkc-hir-def.workspace = true
mlkc-hir-ty.workspace = true
mlkc-line-index.workspace = true
mlkc-lir-wasm.workspace = true
mlkc-mir.workspace = true
mlkc-span.workspace = true
mlkc-stdlib.workspace = true
mlkc-syntax.workspace = true
mlkc-vfs.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-encoder.workspace = true
wasmparser.workspace = true
wasmprinter.workspace = true

[dev-dependencies]
serde_json.workspace = true
wasmtime.workspace = true

[lints]
workspace = true
