[package]
name = "stdx"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
backtrace = { workspace = true, optional = true }
crossbeam-channel.workspace = true
crossbeam-utils.workspace = true
itertools.workspace = true
jod-thread.workspace = true
tracing.workspace = true
# Think twice before adding anything here

[target."cfg(unix)".dependencies]
libc.workspace = true

[target."cfg(windows)".dependencies]
miow.workspace = true
windows-sys.workspace = true

[features]
# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
force-always-assert = []

[lints]
workspace = true
